todo:
  replicaCount: 2
  revisionHistoryLimit: 1
  image:
    repository: baloisegroup/todo-list-example
    tag: 0.1.0
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi
